### ISSUE TITLE
Mysticism - A Magic Overhaul

### ISSUE THREAD

**Issue by justindz** [tiltedphoques/Mod-Compatibility#112]
# Mod information

Mysticism is the parent mod for a series of minimalistic overhauls. A subset of the mod series was tested together and is documented here for ease of use. See Additional Information, below, for a list and testing notes. If commenters believe this should be split out to distinct issues by sub-mod, can do.

#### Download link
https://www.nexusmods.com/skyrimspecialedition/mods/27839

#### Dependencies

None. The mods in the series noted below require Mysticism, so they must be used together. But Mysticism does not list any dependencies.

# Compatibility

> Mod is compatible

# Additional Information

> Tested the following combination of mods:

- Mysticism
- Adamant
- Hand to Hand - An Adamant Addon
- Aetherius
- Mundus
- Apothecary
- Thaumaturgy
- Pilgrim

> Testing consisted of two players on LAN using an identical mod list created with Wabbajack, completing Helgen with fresh characters, connecting to the server and completing the following general play sequence:

- Following Alvor to Riverwood
- Traveling to Whiterun
- Starting the Bleak Falls Barrow quest from Jarl Balgruf
- Taking Bjorlam's cart to Winterhold
- Completing the College of Winterhold entrance quest up to, but not including, entering the Hall of Elements
- Fast traveling to Riverwood
- Completing Bleak Falls Barrow
- Returning the Dragonstone to Farengar

> The following notable things were done to validate mod-related stability:

- Played two separate races, Imperial and High Elf
- Verfied the Security skill tree is present and successfully used Lockpicking (part of Security)
- Verfied the Hand to Hand skill tree is present, allocated the first skill, and played one character entirely as a Hand to Hand fighter
- Confirmed that health, stamina, and magicka potions use the Apothecary logic and functioned correctly when used by players and NPCs
- Used the Guardian Stones, though these may not be a full test of Mundus, as they appear unmodified from vanilla
- Used enchanting table and disenchanted items, including non-vanilla enchantments
- Purchased, equipped, and used items with non-vanilla enchantments
- Both players used Shrine of Talos, but did not test Pray
- Leveled characters to 7 and 8, allocating a variety of perks across the tree, including magic, combat, and crafting (side note: including smithing with Ars Metallica)
- Fought OBIS bandits who used non-vanilla spells, such as Poison Spray, from Mysticism

> Mods in the Mysticism series that were not used:

- Arena
- Blade and Blunt
- Scion
- Manbeast

**Comment by Freakyraf** [comment]
How is OBIS working for you ?

**Comment by justindz** [comment]
So far, only the fights leading up to and inside Bleak Falls Barrow, as far as testing. Didn't notice any "play" compatibility issues there. Mostly, we got our rear ends handed to us in a Dwemer pan. I wanted to run into a "random" OBIS encounter and not just a guaranteed bandit pod and see how that goes, then probably do a post for it if someone else hasn't by then (also have some unrelated tweaks to make to the Wabbajack list probably in parallel).

**Comment by Astral3** [comment]
Mods should be reported individually, not as a group. Also, please pay attention to the mod you are reporting and try not to stray onto other topics. 
You should report on spell synchronization, whether things like unlock spells sync, any issues with mark and recall, etc.

**Comment by DJLegends1011** [comment]
obis will lead to random npcs on both ends so best to drop it till proper support for it

**Comment by DJLegends1011** [comment]
also why the hell does folks keep on saying that simon mods are minimalist/vanilla plus?!
