### ISSUE TITLE
Precision - Accurate Melee Collisions

### ISSUE THREAD

**Issue by smallbutfine** [tiltedphoques/Mod-Compatibility#157]
# Mod information
Physically accurate, true Havok collisions for melee. Procedural, physics-based hit reactions. Weapon trails. Hitstop and camera shake. Recoils when hitting certain materials. Supports both first person and third person, as well as other NPCs and creatures.

#### Download link
https://www.nexusmods.com/skyrimspecialedition/mods/72347

#### Dependencies

- Address Library for SKSE Plugins
https://www.nexusmods.com/skyrimspecialedition/mods/32444
- MCM Helper
https://www.nexusmods.com/skyrimspecialedition/mods/53000
- SkyUI
https://www.nexusmods.com/skyrimspecialedition/mods/12604

# Compatibility

> Mod is compatible in default configuration out of the box. Looks and feels great in STR.

# Additional Information

> Nemesis is a soft requirement, that we omitted. The mod works great without.
> No noticable problems with a few hours testing in STR in default configuration, two players.

**Comment by Astral3** [comment]
This mod already has a post. Please check before posting a compatibility report in order to avoid duplicates.

**Comment by Dragonissa** [comment]
https://github.com/tiltedphoques/Mod-Compatibility/issues/57
