### ISSUE TITLE
Actor Limit Fix

### ISSUE THREAD

**Issue by terrylava** [tiltedphoques/Mod-Compatibility#17]
# Mod information

#### Download link

https://www.nexusmods.com/skyrimspecialedition/mods/32349

#### Dependencies

- SKSE
  -  http://skse.silverlock.org/

# Compatibility

*For example:*
> Mod is not compatible 

# Additional Information

Doesn't allow user to bring up the Skyrim Together control panel

**Comment by Para0x** [comment]
This mod is not the cause of that. There's occasionally an issue with the ST control panel not showing up if you open in Third Person first - it is not connected to Actor Limit Fix.

**Comment by ghost** [comment]
Mod is compatible, I use it without any problem.

**Comment by Pingu-Pox** [comment]
> This mod is not the cause of that. There's occasionally an issue with the ST control panel not showing up if you open in Third Person first - it is not connected to Actor Limit Fix.

@[terrylava](https://github.com/terrylava) please double-check and edit original post

**Comment by terrylava** [comment]
not bugged
