### ISSUE TITLE
Dyndolod

### ISSUE THREAD

**Issue by Waflu648** [tiltedphoques/Mod-Compatibility#172]
# Mod information

#### Download link
https://dyndolod.info

#### Dependencies

- SKSE
  -  http://skse.silverlock.org/
- PapyrusUtil (Optional)  
  -  https://www.nexusmods.com/skyrimspecialedition/mods/13048
# Compatibility

> When Dyndolod is generated and its output enabled, Skyrim Together just gets stuck on ILS.
Everything works fine with SKSE launcher, no issues whatsoever. No other mod in load order has effect on the result.

# Additional Information

>  Console/log with some readable info would be nice.

**Comment by DJLegends1011** [comment]
dyndolod works with str for latest version wth you talking about??

**Comment by Waflu648** [comment]
Thanks for the info, could not find any confirmation that Dyndolod works. Tried playing with it a little and found out the issue is caused by a Synthesis patcher that enables combat in water. Specificaly named - SynCombatBoundaries -

As name implies, it removes combat boundary flag from certain zones and that along with Dyndolod and STR causes infinite loading screens.
Just removing the flags from the patcher is enough to make it work again.

Hopefuly this will help some1, cheers.

**Comment by Waflu648** [comment]
Fixed as stated in comment above.
