### ISSUE TITLE
Face bugged in STR when using modded followers or mods which change the appearance of npc's

### ISSUE THREAD

**Issue by Gollum0002** [tiltedphoques/Mod-Compatibility#181]
![262175138-86b680cd-93a6-4edd-92fa-fd03becf87fa](https://github.com/tiltedphoques/Mod-Compatibility/assets/109045152/c1bd0744-e23e-45f2-9e54-01cf10098f55)

This is an image of the follower mod Recorder taken in Skyrim together reborn.

![262175214-f72ba6a2-f112-4584-ae14-65cd6ae288c3](https://github.com/tiltedphoques/Mod-Compatibility/assets/109045152/3dab47a1-b1d5-4616-a9ed-e58821410eff)

This is an image of the same follower mod taken in skse64_loader.exe.

This issue also affects vanilla npc's when their appearance is changed by other mods...
For example, Bijin Wives, Bijin Npc's and Bijin Warmaidens. Their appearances does not match the ones shown on the Mod's page (FYI I have used these mods before so it is very easy to notice the difference)

Not using any mods which may alter character appearances. Load order attached below.

[loadorder.txt](https://github.com/tiltedphoques/Mod-Compatibility/files/12419376/loadorder.txt)

**Comment by DJLegends1011** [comment]
this is due to devs disabling custom facegen which they thought broke player facegen but it actually did more harm than good if ya want a fix get rid of the commit and any face replacer works fine

**Comment by lainussash** [comment]
Having the same issue as well. I also installed Bijin Npcs. Some of them looked right but the others had wired inflated faces.
I also noticed that there were some loading failures at the mean time.
"MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkhood_f.tri
MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkrobes_f.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkboots_f.tri
MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkhood_f.tri
MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkrobes_f.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkboots_f.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\torsof.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\shoesf.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\torsof.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\shoesf.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes04\robef.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes04\bootsf.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes04\robef.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes04\bootsf.tri
MorphCache::CacheFile - Failed to load meshes\clothes\blacksmith\f\torso.tri
MorphCache::CacheFile - Failed to load meshes\clothes\blacksmith\f\shoes.tri
MorphCache::CacheFile - Failed to load meshes\clothes\blacksmith\f\torso.tri
MorphCache::CacheFile - Failed to load meshes\clothes\blacksmith\f\shoes.tri
MorphCache::CacheFile - Failed to load meshes\clothes\barkeeper\f\torso.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\barkeeper\f\shoes.tri
MorphCache::CacheFile - Failed to load meshes\clothes\barkeeper\f\torso.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\barkeeper\f\shoes.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\dress.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\shoes.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\dress.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\shoes.tri
MorphCache::CacheFile - Failed to load meshes\clothes\merchantclothes\torsof.tri
MorphCache::CacheFile - Failed to load meshes\clothes\merchantclothes\bootsf.tri
MorphCache::CacheFile - Failed to load meshes\clothes\merchantclothes\torsof.tri
MorphCache::CacheFile - Failed to load meshes\clothes\merchantclothes\bootsf.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\torsof.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\shoesf.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\torsof.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\shoesf.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\dress.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\shoes.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\dress.tri
MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri
MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\shoes.tri
MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrarmorfemale.tri
MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrgauntletsfemale.tri
MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrbootsfemale.tri
MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrarmorfemale.tri
MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrgauntletsfemale.tri
MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrbootsfemale.tri
MorphCache::CacheFile - Failed to load meshes\armor\hide\f\cuirassheavy.tri
MorphCache::CacheFile - Failed to load meshes\armor\hide\f\bootsheavy.tri
MorphCache::CacheFile - Failed to load meshes\armor\hide\f\cuirassheavy.tri
MorphCache::CacheFile - Failed to load meshes\armor\hide\f\bootsheavy.tri"
It would be really helpful if you can tell me that is there any way to solve this issue right now?

**Comment by DJLegends1011** [comment]
> Having the same issue as well. I also installed Bijin Npcs. Some of them looked right but the others had wired inflated faces. I also noticed that there were some loading failures at the mean time. "MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkhood_f.tri MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkrobes_f.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkboots_f.tri MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkhood_f.tri MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkrobes_f.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\monk\monkboots_f.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\torsof.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\shoesf.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\torsof.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\shoesf.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes04\robef.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes04\bootsf.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes04\robef.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes04\bootsf.tri MorphCache::CacheFile - Failed to load meshes\clothes\blacksmith\f\torso.tri MorphCache::CacheFile - Failed to load meshes\clothes\blacksmith\f\shoes.tri MorphCache::CacheFile - Failed to load meshes\clothes\blacksmith\f\torso.tri MorphCache::CacheFile - Failed to load meshes\clothes\blacksmith\f\shoes.tri MorphCache::CacheFile - Failed to load meshes\clothes\barkeeper\f\torso.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\barkeeper\f\shoes.tri MorphCache::CacheFile - Failed to load meshes\clothes\barkeeper\f\torso.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\barkeeper\f\shoes.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\dress.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\shoes.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\dress.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\shoes.tri MorphCache::CacheFile - Failed to load meshes\clothes\merchantclothes\torsof.tri MorphCache::CacheFile - Failed to load meshes\clothes\merchantclothes\bootsf.tri MorphCache::CacheFile - Failed to load meshes\clothes\merchantclothes\torsof.tri MorphCache::CacheFile - Failed to load meshes\clothes\merchantclothes\bootsf.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\torsof.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\shoesf.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\torsof.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes01\shoesf.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\dress.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\shoes.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\dress.tri MorphCache::CacheFile - Failed to load meshes\actors\character\character assets\femalehands.tri MorphCache::CacheFile - Failed to load meshes\clothes\farmclothes02\f\shoes.tri MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrarmorfemale.tri MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrgauntletsfemale.tri MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrbootsfemale.tri MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrarmorfemale.tri MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrgauntletsfemale.tri MorphCache::CacheFile - Failed to load meshes\armor\draugr\draugrbootsfemale.tri MorphCache::CacheFile - Failed to load meshes\armor\hide\f\cuirassheavy.tri MorphCache::CacheFile - Failed to load meshes\armor\hide\f\bootsheavy.tri MorphCache::CacheFile - Failed to load meshes\armor\hide\f\cuirassheavy.tri MorphCache::CacheFile - Failed to load meshes\armor\hide\f\bootsheavy.tri" It would be really helpful if you can tell me that is there any way to solve this issue right now?

pleae read what I said above. devs will sadly never fix it since no mod support

**Comment by Dragonissa** [comment]
This is not a bug reporting forum.
