### ISSUE TITLE
Unofficial Skyrim Special Edition Patch (TEST 2)

### ISSUE THREAD

**Issue by TinnyPiano26** [tiltedphoques/Mod-Compatibility#184]
### USSEP (Unofficial Skyrim Special Edition Patch)

> [Unofficial Skyrim Special Edition Patch on Nexusmods](https://www.nexusmods.com/skyrimspecialedition/mods/266).

### Testing Environment

> Our testing was conducted using a modded animation-compatible build based on 1.6.3, specifically the [rfortier fork](https://github.com/rfortier/TiltedEvolution-rwf/tree/feat-modded-anim-compat-master).
This build includes modifications for vanilla variable case-sensitivity checks to ensure that, when modded animations are present, variations in vanilla variable case formatting do not result in un-synced animation variables. [This is the branch we built from](https://github.com/MostExcellent/TiltedEvolutionModdedAnim/tree/rwf-modded-anim-compat-master-case-checks).
The testing environment included 4 free creations, Realm of Lorkhan, and Unofficial Skyrim Modder's Patch.

#### Realm of Lorkhan
> [Realm of Lorkhan](https://www.nexusmods.com/skyrimspecialedition/mods/18223)

#### USMP
> [Unofficial Skyrim Modder's Patch](https://www.nexusmods.com/skyrimspecialedition/mods/49616)

### Test Results

> Over a testing period of 1 hour and 10 minutes, involving two players, we observed no crashes on new game starts or loaded saves. There was minimal desynchronization between players when USSEP and STR were properly installed and ordered, suggesting good initial compatibility. However, further testing is required, particularly concerning the scripts edited by USSEP and their operation within STR.

## Conclusion

> Initial testing shows promising compatibility between USSEP and Skyrim Together Reborn, with no significant issues encountered during our short playthrough. Had lots of fun with the playtest sessions, but will need more testing if the scripts that were edited by USSEP actually work with STR.

**Comment by Dragonissa** [comment]
Duplicate. Share your findings their please. https://github.com/tiltedphoques/Mod-Compatibility/issues/7
