### ISSUE TITLE
Collection made for Skyrim Together

### ISSUE THREAD

**Issue by connorx2000** [tiltedphoques/Mod-Compatibility#19]
# Mod information

#### Download link
https://next.nexusmods.com/skyrimspecialedition/collections/oabb7c?tab=mods

#### Dependencies
- Nexus Collection

# Compatibility

> Will take a while to fully check, thought i would post it so others can be made aware and help.

# Additional Information

> Good base collection for texture overhual might be outdated.

**Comment by Astral3** [comment]
While we appreciate the advertisement and what you're trying to do, this does not belong here as it is not a compatibility report. 

@Dragonisser 
@RobbeBryssinck
