### ISSUE TITLE
Unofficial Patch/CBBE

### ISSUE THREAD

**Issue by CrazyMaze10101** [tiltedphoques/Mod-Compatibility#24]
Mods: Unofficial Skyrim Special Edition Patch/CBBE

https://www.nexusmods.com/skyrimspecialedition/mods/266?tab=files (Unofficial Patch)
https://www.nexusmods.com/skyrimspecialedition/mods/198/?tab=files (CBBE, has a mature filter)

Dependencies
- SKSE?

Compatibility
The Unofficial Patch is only "incompatible" because we have ModPolicy on. When we have the most updated version, regardless of if the server host's version of the patch is copy and pasted into the server's mod folder (a "Data" folder I made where the mod is, I looked at the wiki, and all other mods are just fine), it still says the server doesn't have the mod, and that we can't connect unless it's removed. However, an older version can bypass this entirely? (Such as my friend can connect to the server with this older version, and the server having the updated version, and it gives no errors, but I can't connect with the most updated version) So, my friend gave me their older version and now the server lets us in, now that I have an older version on client and server.
For CBBE, I'm not sure if it's "incompatible". It works fine client side, but others can't see your custom-made morphed body. I'm not sure if this can be fixed, but it'd be amazing if it could be seen across clients. And yes, the mod is installed on the server too, so it's not an issue on if the mod needs it server side to show it to other players, like I had thought.

Additional Information
I'm not sure how these can be fixed, or if they even can or if you guys don't even want to touch them, but it'd be cool if they could. Perhaps I put the mods on the server wrong? I used Mod Organizer 2 to install the Together mod, then went in its files, made the "Data" folder, and copy and pasted my client mods to the server's Data folder, and made sure to copy my loadorder.txt file from my client to server Data folder as well, to make sure nothing was mistyped or misplaced. If this isn't the issue, then I would assume it's just an issue of the mods not syncing, and again, not sure if it can be touched/fixed, but I might as well make this post in case others also want to use either of these mods and have similar issues.

I will attach a photo of my "haha funny" character from my POV, and my friends to showcase the CBBE. I didn't really think to get a screenshot of the server logs for the Unofficial Patch, so if you want, I can add that on later. It'll be pretty obvious what the body morph I made will be.
![Friends POV](https://user-images.githubusercontent.com/108965513/178090376-cb07aab9-12af-464b-a41b-89daa2d750d8.png)
![My POV](https://user-images.githubusercontent.com/108965513/178090384-b2609a56-b835-4b3f-976a-2548597d21a2.png)

**Comment by Astral3** [comment]
..So, first of all, this doesn't really seem to belong in this section. This is for compatiblity, not requests. We don't care about your modpolicy settings, this section is only for whether a mod breaks Skyrim Together.

We will not be synchronizing sliders outside of those in vanilla.

If you intend to post here in the future, please follow the guidelines instead of dumping text, keep it to one mod per post, and do not talk about unrelated matters. 

I'd like to ask @RobbeBryssinck to delete or close this thread.
