### ISSUE TITLE
Immersive & Pure Collection Partial Compatibility

### ISSUE THREAD

**Issue by csrZombie** [tiltedphoques/Mod-Compatibility#27]
# Mod information

#### Download link
*For example:*
https://next.nexusmods.com/skyrimspecialedition/collections/gqoewd

#### Dependencies

See Download

# Compatibility

In Progress - Please comment any compatibility info you find out with this collection
TrueDirectionMovement may be the cause of sliding

# Additional Information

Alternate Conversation Camera -  Error on Launch - disable
Engine fixes part 1 and 2 - disable - select No when asked to exit game on launch

This should get you started with a crazy immersive experience with, so far, only one issue. Other players do not have the custom animation applied and slide around. This does not apply to third person animations of the client player so I assume it has to do with entity types. Still working on finding which animation mod causes the issue as it is the only immersion breaking mod I have tested so far. Preliminary testing has verified that the game works all the way up to joining a server and meeting up with another player. Potential issues may crop up later. For now, a quick suite of mods that is easy to download and install via vortex.

**Comment by Dragonissa** [comment]
This is meant for single mods, not collections.

**Comment by csrZombie** [comment]
> This is meant for single mods, not collections.

was recommended to post here from the discord, leave it, gives a good starting point for finding what works and experimenting with what doesn't.
