### ISSUE TITLE
Ruins Clutter Improved

### ISSUE THREAD

**Issue by smallbutfine** [tiltedphoques/Mod-Compatibility#46]
#Texture and Mesh mod.
 Provokes client crash to desktop right on the cobblestone way from Helgen cave exit to Riverwood. Probably due to some mesh change. Tested on 2 clients, repeatable issue. Errors at other places possible.

# Compatibility

 Mod is not compatible to Skyrim Together Reborn.

**Comment by Grimmspecter** [comment]
Has anyone else tested this? Confused on why mesh and texting mod would cause issues

**Comment by Dragonissa** [comment]
1. Not following the Issue Template
2. As @Grimmspecter mentioned, pretty much doubting that this will cause any issues.

Change it to the original template.
