### ISSUE TITLE
Smooth Camera Fatal Error

### ISSUE THREAD

**Issue by Gollum0002** [tiltedphoques/Mod-Compatibility#64]
# Mod information

#### Download link
https://www.nexusmods.com/skyrimspecialedition/mods/41252?tab=description

#### Dependencies

*For example:*
- SKSE64
- Address Library for SKSE Plugins
- SkyUi

# Compatibility

Skyrim Together gives Fatal error [Failed to place detour on target function(Detours::FactorCameraOffset), This error is fatal] when loading saves with the mod enabled. Works on just SKSE but not with Skyrim Together.

![Screenshot (68)](https://user-images.githubusercontent.com/109045152/178163497-f1161648-db3d-4b28-be2e-f793b082d436.png)

**Comment by Astral3** [comment]
This is a duplicate post of #10 and is unnecessary. Please check for existing compatibility reports before opening your own.

@RobbeBryssinck Please close as duplicate

**Comment by NoNutNed** [comment]
I made a compatibility report earlier, if you check the first page. Someone posted a lil workaround.

**Comment by Dragonissa** [comment]
duplicate https://github.com/tiltedphoques/Mod-Compatibility/issues/10
