### ISSUE TITLE
(NEMESIS) Project New Reign - Nemesis Unlimited Behavior Engine

### ISSUE THREAD

**Issue by SketchFoxsky** [tiltedphoques/Mod-Compatibility#80]
# Mod information

#### Download link
https://www.nexusmods.com/skyrim/mods/87642

#### Dependencies

[C++ redistributable 2019](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

# Compatibility

> Mod is not compatible and will have multiple Behavior issues
# Additional Information

> All Mods relying on Nemesis should be avoided at this time.

**Comment by Dragonissa** [comment]
Duplicated https://github.com/tiltedphoques/Mod-Compatibility/issues/31
