### ISSUE TITLE
RaceMenu

### ISSUE THREAD

**Issue by VENDETTA5** [tiltedphoques/Mod-Compatibility#82]
# Mod information

#### Download link
https://www.nexusmods.com/skyrimspecialedition/mods/19080?tab=files

#### Dependencies
None
# Compatibility
The new model syncs quite well but the mod may provoke some serious issues... My friend runs this mod with only 10 mods installed and it used to crash every time on loading screens until he removed it. I run all the same mods + 190 more and my game hasn't crashed even once during playtime.

**Comment by Dragonissa** [comment]
Duplicate https://github.com/tiltedphoques/Mod-Compatibility/issues/37
